### ISSUE TITLE
Something strange is happening here

### ISSUE THREAD

**Issue by Piterden** [Tucsky/SignificantTrades#10]
@Tucsky, first I wanted to tell you well done! Your [branch](https://github.com/Tucsky/SignificantTrades/tree/feature/standalone) is a good code!

However, there is a bit of remark:

- Why do you crap into the global window object? Stop it, please. You can easily move those functions from the window to the root vue-component as methods, then using them through this.$root.yourKillishMethod(kill, ish) call.
- You could make mounted event asynchronous with async statement before declare, then use await spaghetti instead of nesting functions spaghetti.
- Wait a minute, so you want to say that eventemitter is the helper, but websocket is the service near the options?
You know what?
websocket and eventemitter are such things which provide you a new information, like the dynamic shit.
options just store some information for you and it is the static info.
So, obivuosly options is the store (state is the store too, btw) and websocket and eventemitter is relative essentially, but of course not the same. They may be called services, but I believe it is a superfluous term in web-dev. Helpers I like much more. But it is your decision.

_How do you like that second one?_

**Comment by Tucsky** [comment]
Very informative thank you my man ! I like this.
This is my first vuejs project, I just learn as I code :)

Didn't know about this.$root, I will give it a try 👍 

The Eventemitter polyfill, I just realized that it is still here, was an attempt to use the same exchanges classes for the server and the client (as nodejs use it natively but browser dont). Then I got rid of all server parts from that branch. Are you suggesting that I should make the Exchange class a Vuejs EventBus ? That would make a lot of event bus, socket options and one for each exchanges, is it faster than using this helper for emiting/listing to events ?

Then comes options. One big issue is that every components are super connected to each others and needs to know what options is up to at any time. The main changes to the options object are made in settings.vue, and this is what I did this in the component to get access to everything https://github.com/Tucsky/SignificantTrades/blob/feature/standalone/src/components/Settings.vue#L169 . Do you think this is the way to go ? Or should I use specifics setters, getters and events for every properties of options and duplicate options properties in settings.vue instead of linking the whole options eventbus in the component data ? I also created a "change" events on options.js so I didn't had to create too many events, no so proud about that too. https://github.com/Tucsky/SignificantTrades/blob/feature/standalone/src/components/TradeChart.vue#L414 (here TradeChart listen to option change)

The whole reference options into component data to use with v-model doesnt work every time, https://github.com/Tucsky/SignificantTrades/blob/feature/standalone/src/components/Settings.vue#L226 see here in the Settings panel for each exchanges there is a input suppose to control "options.exchangeThresholds[*exchangeid*]" So I couldn't use v-model="options.exchangeThresholds[exchange]" apparently because only "_exchangeThresholds_" property was reactive but not _exchangeThresholds[exchange]_ (?)
So I update options.exchangeThresholds[exchange] using Vue.set when range input is changed, options seemed be updated but template did not for some reason, and I needed to duplicate the exchangeThresholds property in Settings.vue and update both of them using Vue.set...
![image](https://user-images.githubusercontent.com/5738336/44577273-f279d500-a790-11e8-89d0-7eceac152f08.png)

> You could make mounted event asynchronous with async statement before declare, then use await spaghetti instead of nesting functions spaghetti.

No really sure what you mean about this one sorry...

**Comment by Piterden** [comment]
```js
'abc=22&ghu=sdsds&jjii=223'.split('&').reduce((acc, cur) => { const curArr = cur.split('='); acc[curArr[0]] = curArr[1]; return acc }, {})
// {abc: "22", ghu: "sdsds", jjii: "223"}
```
