### ISSUE TITLE
Where to get the sounds?

### ISSUE THREAD

**Issue by rranke** [Tucsky/SignificantTrades#12]
I just crawled the source code 1minute, but couldnt find them...

and... why do the sounds not play on iphone?!

best regards

**Comment by Piterden** [comment]
https://github.com/Tucsky/SignificantTrades/blob/master/client/src/services/sfx.js

**Comment by Tucsky** [comment]
- Sound is generated using waves oscillators from WebAudioAPI, and if you are not using chrome [the result might not be that great unfortunately...](https://stackoverflow.com/questions/29378875/how-can-i-avoid-this-clicking-sound-when-i-stop-playing-a-sound), I wonder if using pre synthetized midi sound for the *bip* and transpose it using webaudio api would a better approach?
- As for the "not playing at all" issue, webaudio require clear user gestures in order to enable the sound on the browser. Maybe [this](https://hackernoon.com/unlocking-web-audio-the-smarter-way-8858218c0e09) will fix the issue, can't test on iOS myself tho
