### ISSUE TITLE
[Request] Exchange specific thresholds

### ISSUE THREAD

**Issue by RandomErrorMessage** [Tucsky/SignificantTrades#2]
I'd like to set higher thresholds for BitMEX :)

**Comment by Tucsky** [comment]
see https://github.com/Tucsky/SignificantTrades/tree/feature/standalone

**Comment by Piterden** [comment]
@Tucsky, first I wanted to tell you well done! Your branch is a good code!

However, there is a bit of remark:

- Why do you crap into the global window object? Stop it, please. You can easily move those functions from the window to the root vue-component as methods, then using them through `this.$root.yourKillishMethod(kill, ish)` call.
- You could make mounted event asynchronous with `async` statement before declare, then use `await` spaghetti instead of nesting functions spaghetti.
- Wait a minute, so you want to say that `eventemitter` is the helper, but `websocket` is the service near the `options`?
You know what?
`websocket` and `eventemitter` are such things which provide you a new information, like the dynamic shit.
`options` just store some information for you and it is the static info.
So, obivuosly `options` is the store (state is the store too, btw) and `websocket` and `eventemitter` is relative essentially, but of course not the same. They may be called services, but I believe it is a superfluous term in web-dev. Helpers I like much more. But it is your decision.
