### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by ctanbern** [Tucsky/SignificantTrades#30]
HIHI. Thats tool is really usefull, but can I suggest you add more history(maybe 1h or 4h) lookback?
Also, is there can be added trade per minutes counter as graphs bar?(visually mostly the same as buy/sell rn) but without emas.
Thanks!

**Comment by Tucsky** [comment]
Hey! I would love too have that feature too :(
This app is running on top of trades infos, like uncompressed raw trades. And with more than 1M trades per day its just not possible atm for the average browser to run a 4H chart on this app even a 15m would crash most browsers, not to mention the DATA to download etc...

That said its not impossible either, had this idea months ago... I could change the way the app process the info, instead of raw trade directly stack them as they come, into 10s or 5s tick PER EXCHANGES. 
each one would have the following props
- buy amount (+ currency)
- buy count
- sell amount (+ currency)
- sell count
- ohlc
Then use thoses as a base to create 15m 1h 4h 1d candles.
Server part would need some changes accordingly, influxdb would be primed for that kind of thing, imo, bulk insert trades every minute and continuous queries to preload a few timeframes on the background. Lot of work 😩 But do-able
