### ISSUE TITLE
Problem with build

### ISSUE THREAD

**Issue by adrpan** [Tucsky/SignificantTrades#84]
Hello, i tried install this on my server, after npm install i make npm run build, and i recive that error.
Someone can help with that?

npm -v 6.14.4
node -v v8.10.0

last lines npm install look that:
`adrpan@dedi-par-56180:/var/www/trader.gq$ npm install
npm WARN webpack-dev-middleware@1.12.2 requires a peer of webpack@^1.0.0 || ^2.0.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN webpack-dev-server@2.11.5 requires a peer of webpack@^2.2.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 24265 packages in 10.429s

26 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
`

[2020-04-12T20_40_22_862Z-debug.log](https://github.com/Tucsky/SignificantTrades/files/4467065/2020-04-12T20_40_22_862Z-debug.log)

**Comment by Tucsky** [comment]
Hello, thats a little weird of an issue, i'd suggest remove the node_modules folder and package-lock.json then npm install again.
Made a fresh install today as my ssd litteraly died yesterday 😢 
And haven't seen any issues during the npm install

However, Ive been using a fork of lightweight-charts since not so long ago, so in case removing node_modules folder didn't helped you can try
`rm -rf node_modules/ && rm -rf package-lock.json`
`npm uninstall lightweight-charts`
`npm install`
`npm install git://github.com/Tucsky/lightweight-charts.git --ignore-scripts`

let me know if that does the trick :)

**Comment by adrpan** [comment]
yep it worked but when its on folder with name SignificantTrades. When this script doesnt in folder with name SignificantTrades npm cant install script and run after that, same problem i have on my desktop with W10 x64.
