### ISSUE TITLE
Not working on amazon EC2

### ISSUE THREAD

**Issue by huzoorbux** [Tucsky/SignificantTrades#91]
I have configured it on amazon ec2 but its giving me this error 

`[ftx] unknown pair EC2-52-90-159-65`

**Comment by Tucsky** [comment]
I suspect this is due to https://github.com/Tucsky/SignificantTrades/blob/1688f4c1b1079e9929ab9c0ace9024751021a4f2/src/store/settings/state.js#L38

This basicaly consider the subdomain as a pair for easy access (ex ethusd.aggr.trade automaticaly set pair as ETHUSD in the store...) 
And this behavior shouldn't be active on custom installations
I pushed a fix to limit these lines to aggr.trade only

**Comment by huzoorbux** [comment]
Thanks, it's working now.
